name: pearshare
description: Food WAStage reduction
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6
  camera: "^0.2.0"
  path_provider: "^0.4.0"
  video_player: "^0.5.2"
  http: "^0.11.3+16"
  cryptoutils: "^0.3.0"
  math_expressions: "^0.3.0"
  crypto: any

  cupertino_icons: ^0.1.0
  shrine_images: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/green_pear.png
    - assets/white-transparent.png
    - assets/red-transparent.png
    - assets/blue.png
    - assets/new-green.png
    - assets/orange.png
    - assets/new-green-hollow-circle.png
    - assets/slanted_menu.png
    - assets/3-0.png
    - assets/0-0.png
    - assets/1-0.png
    - assets/2-0.png
    - assets/3-0.png
    - assets/4-0.png
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Thin.ttf
    - family: Raleway2
      fonts:
        - asset: fonts/Raleway-Bold.ttf
    - family: Raleway3
      fonts:
        - asset: fonts/Raleway-Medium.ttf
